apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-ego-server
  labels:
    app: vault-ego-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-ego-app
  template:
    metadata:
      labels:
        app: vault-ego-app
    spec:
      tolerations:
      - key: kubernetes.azure.com/sgx_epc_mem_in_MiB
        operator: Exists
        effect: NoSchedule
      containers:
      # This is the image used to run vault with ego. 
      # You will find the Dockerfile in another section of this project. 
      # You should build that Dockerfile an push the image to a repository on Docker Hub.       
      - name: vault-ego-helm-chart
        image: marvinwolf/ego-vault-test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8200
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 100
